services:
  db:
    image: postgres:16
    container_name: teacher_portal_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: stafilo
      POSTGRES_DB: teacher_portal
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
